// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqxkjgslyyvlooindhxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxeGtqZ3NseXl2bG9vaW5kaHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyODAxNDksImV4cCI6MjA1Mjg1NjE0OX0.G5lTP3e2C6iB4g9-wU9SUWqpGeCRoUoP1fKkFhwRYlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);